# Generated by Django 3.2.5 on 2021-09-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='token',
            new_name='token_type',
        ),
    ]
